window.TRAKK_BOOTSTRAP = {
  "storageKey": "trakk-4d-uat-state-v2",
  "version": "0.11.0-4d-uat.3",
  "buildLabel": "4D UAT",
  "appTitle": "4D Dance Trakk",
  "selectedSessionId": "4d_uat_2026_07_20",
  "members": [
    {
      "id": "4d_member_001",
      "clubId": "club_001",
      "firstName": "Aaron",
      "lastName": "Grierson",
      "email": "agrierson01@gmail.com",
      "phone": "0452 273 520",
      "emergencyContactName": "Zelda",
      "emergencyContactPhone": "0403 000 000",
      "status": "active",
      "pricingLabel": "Groupon",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Term 2, Special, Term 3, Mid Year Party",
      "sourceAttendanceCount": 14,
      "postcode": "5000",
      "emergencyContactRelationship": "Mother"
    },
    {
      "id": "4d_member_051",
      "clubId": "club_001",
      "firstName": "Abby",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Party",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Mid Year Party",
      "sourceAttendanceCount": 0
    },
    {
      "id": "4d_member_038",
      "clubId": "club_001",
      "firstName": "Adam",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Free lesson",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Mid Year Party",
      "sourceAttendanceCount": 1
    },
    {
      "id": "4d_historical_002",
      "clubId": "club_001",
      "firstName": "Andrew",
      "lastName": "Bartlett",
      "email": "nexusglassworx@gmail.com",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from historical student register",
      "sourceAttendanceCount": 0,
      "birthday": "9th Oct",
      "level": "1",
      "dateStarted": "launch party",
      "referralSource": "Thursdays",
      "firstTimersPass": "yes",
      "historicalStatus": "No"
    },
    {
      "id": "4d_member_003",
      "clubId": "club_001",
      "firstName": "Andrew",
      "lastName": "Fort",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Groupon",
      "sessionBalance": 7,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Special, Term 3",
      "sourceAttendanceCount": 2
    },
    {
      "id": "4d_member_042",
      "clubId": "club_001",
      "firstName": "Ann",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Party",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Mid Year Party",
      "sourceAttendanceCount": 1
    },
    {
      "id": "4d_member_002",
      "clubId": "club_001",
      "firstName": "Anna",
      "lastName": "Fort",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Groupon",
      "sessionBalance": 7,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Term 3, Special",
      "sourceAttendanceCount": 2
    },
    {
      "id": "4d_historical_001",
      "clubId": "club_001",
      "firstName": "Anna",
      "lastName": "Kolodina",
      "email": "desanimaux@hotmail.com",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "staff",
      "learningPreference": "Both",
      "notes": "Imported from historical student register",
      "sourceAttendanceCount": 0,
      "birthday": "11th Oct",
      "level": "2",
      "dateStarted": "15/11/2021",
      "firstTimersPass": "no",
      "historicalStatus": "Staff"
    },
    {
      "id": "4d_historical_054",
      "clubId": "club_001",
      "firstName": "Anne",
      "lastName": "Messagean",
      "email": "anne.messagean@gmail.com",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from historical student register · Email note: Address not found",
      "sourceAttendanceCount": 0,
      "historicalStatus": "No"
    },
    {
      "id": "4d_member_005",
      "clubId": "club_001",
      "firstName": "Bec",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Special, Mid Year Party",
      "sourceAttendanceCount": 1
    },
    {
      "id": "4d_historical_004",
      "clubId": "club_001",
      "firstName": "Bek",
      "lastName": "Grayden",
      "email": "bek.grayden@gmail.com",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from historical student register",
      "sourceAttendanceCount": 0,
      "birthday": "18th Apr",
      "level": "2",
      "dateStarted": "launch party",
      "referralSource": "Fb",
      "firstTimersPass": "yes",
      "historicalStatus": "No"
    },
    {
      "id": "4d_historical_003",
      "clubId": "club_001",
      "firstName": "Ben",
      "lastName": "Grayling",
      "email": "bengrayling@gmail.com",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from historical student register",
      "sourceAttendanceCount": 0,
      "historicalStatus": "No"
    },
    {
      "id": "4d_historical_005",
      "clubId": "club_001",
      "firstName": "Bing",
      "lastName": "Liu",
      "email": "shagnoneal@hotmail.com",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from historical student register · Email note: Address not found",
      "sourceAttendanceCount": 0,
      "historicalStatus": "No"
    },
    {
      "id": "4d_member_006",
      "clubId": "club_001",
      "firstName": "Bridgette",
      "lastName": "Hogg",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "8 class pass",
      "sessionBalance": 7,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Term 2, Mid Year Party",
      "sourceAttendanceCount": 1,
      "level": "2",
      "dateStarted": "31/1/2022",
      "firstTimersPass": "no",
      "historicalStatus": "No"
    },
    {
      "id": "4d_member_045",
      "clubId": "club_001",
      "firstName": "Carey",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Party",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Mid Year Party",
      "sourceAttendanceCount": 0
    },
    {
      "id": "4d_historical_007",
      "clubId": "club_001",
      "firstName": "Carol",
      "lastName": "Noble",
      "email": "cmn0605@gmail.com",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from historical student register",
      "sourceAttendanceCount": 0,
      "level": "1",
      "dateStarted": "44658",
      "firstTimersPass": "yes",
      "historicalStatus": "No"
    },
    {
      "id": "4d_member_007",
      "clubId": "club_001",
      "firstName": "Catherine",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Term 1",
      "sourceAttendanceCount": 0
    },
    {
      "id": "4d_member_049",
      "clubId": "club_001",
      "firstName": "Cathy",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Party",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Mid Year Party",
      "sourceAttendanceCount": 0
    },
    {
      "id": "4d_historical_006",
      "clubId": "club_001",
      "firstName": "CeeJay",
      "lastName": "Singh",
      "email": "cjaustralia@gmail.com",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from historical student register",
      "sourceAttendanceCount": 0,
      "level": "2",
      "dateStarted": "launch party",
      "firstTimersPass": "Yes",
      "historicalStatus": "No"
    },
    {
      "id": "4d_historical_052",
      "clubId": "club_001",
      "firstName": "Claire",
      "lastName": "Kelly",
      "email": "clairekelly@gmail.com",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from historical student register",
      "sourceAttendanceCount": 0,
      "dateStarted": "45108",
      "historicalStatus": "No"
    },
    {
      "id": "4d_historical_008",
      "clubId": "club_001",
      "firstName": "Claude",
      "lastName": "Scorronelli",
      "email": "cyscorso@iprimis.com.au",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from historical student register · Email note: Address not found",
      "sourceAttendanceCount": 0,
      "level": "1",
      "dateStarted": "44658",
      "referralSource": "Friend",
      "firstTimersPass": "yes",
      "historicalStatus": "No"
    },
    {
      "id": "4d_historical_051",
      "clubId": "club_001",
      "firstName": "Colin",
      "lastName": "Kelly",
      "email": "colinsk@gmail.com",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from historical student register",
      "sourceAttendanceCount": 0,
      "dateStarted": "45108",
      "historicalStatus": "No"
    },
    {
      "id": "4d_member_040",
      "clubId": "club_001",
      "firstName": "Dale",
      "lastName": "Cox",
      "email": "dalecox777@gmail.com",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Free lesson",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Mid Year Party",
      "sourceAttendanceCount": 1,
      "birthday": "8th May",
      "level": "2",
      "dateStarted": "launch party",
      "firstTimersPass": "Yes",
      "historicalStatus": "Staff"
    },
    {
      "id": "4d_historical_009",
      "clubId": "club_001",
      "firstName": "Damien",
      "lastName": "Presser",
      "email": "damiensp@gmail.com",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from historical student register",
      "sourceAttendanceCount": 0,
      "birthday": "21st Jan",
      "level": "2",
      "dateStarted": "launch party",
      "firstTimersPass": "Yes",
      "historicalStatus": "Sometimes"
    },
    {
      "id": "4d_member_058",
      "clubId": "club_001",
      "firstName": "Daniel",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Party",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Mid Year Party",
      "sourceAttendanceCount": 0
    },
    {
      "id": "4d_member_059",
      "clubId": "club_001",
      "firstName": "Daniel",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Party",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Mid Year Party",
      "sourceAttendanceCount": 0
    },
    {
      "id": "4d_member_041",
      "clubId": "club_001",
      "firstName": "David",
      "lastName": "Radolovic",
      "email": "raddj001@mymail.unisa.edu.au",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Party",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Mid Year Party",
      "sourceAttendanceCount": 1,
      "level": "2",
      "dateStarted": "launch party",
      "referralSource": "414226578",
      "firstTimersPass": "yes",
      "historicalStatus": "No"
    },
    {
      "id": "4d_historical_014",
      "clubId": "club_001",
      "firstName": "Debra",
      "lastName": "Gibson",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from historical student register",
      "sourceAttendanceCount": 0,
      "birthday": "13th Nov",
      "level": "1",
      "dateStarted": "launch party",
      "firstTimersPass": "yes",
      "historicalStatus": "No"
    },
    {
      "id": "4d_historical_010",
      "clubId": "club_001",
      "firstName": "Dung",
      "lastName": "Tran",
      "email": "tranthithuydung@gmail.com",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from historical student register",
      "sourceAttendanceCount": 0,
      "dateStarted": "29/8/2022",
      "referralSource": "Groupon",
      "firstTimersPass": "Yes",
      "historicalStatus": "No"
    },
    {
      "id": "4d_member_012",
      "clubId": "club_001",
      "firstName": "Dylan",
      "lastName": "Horn",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Free lesson",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Free Nights",
      "sourceAttendanceCount": 1
    },
    {
      "id": "4d_member_009",
      "clubId": "club_001",
      "firstName": "Eranga",
      "lastName": "Kompannage",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Term pass",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Term 2",
      "sourceAttendanceCount": 0
    },
    {
      "id": "4d_member_024",
      "clubId": "club_001",
      "firstName": "Eranga",
      "lastName": "Sudeshini",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Free lesson",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Free Nights",
      "sourceAttendanceCount": 1
    },
    {
      "id": "4d_historical_011",
      "clubId": "club_001",
      "firstName": "Ewa",
      "lastName": "Bradden",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from historical student register",
      "sourceAttendanceCount": 0,
      "birthday": "7th Mar",
      "level": "2",
      "dateStarted": "44745",
      "firstTimersPass": "Yes",
      "historicalStatus": "No"
    },
    {
      "id": "4d_historical_015",
      "clubId": "club_001",
      "firstName": "Faith",
      "lastName": "Paredes",
      "email": "paredesaf@hotmail.com",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from historical student register",
      "sourceAttendanceCount": 0,
      "birthday": "23rd Mar",
      "level": "1",
      "dateStarted": "22/11/2021",
      "referralSource": "CJs friend",
      "firstTimersPass": "yes",
      "historicalStatus": "No"
    },
    {
      "id": "4d_member_010",
      "clubId": "club_001",
      "firstName": "Fiona",
      "lastName": "Clewes",
      "email": "tbanoif@hotmail.com",
      "phone": "0432 583 048",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Free Nights, Term 1, Special, Term 2, Term 3",
      "sourceAttendanceCount": 4,
      "postcode": "5046"
    },
    {
      "id": "4d_historical_055",
      "clubId": "club_001",
      "firstName": "Florian",
      "lastName": "Olivero",
      "email": "florian.olivero@gmail.com",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from historical student register · Email note: Address not found",
      "sourceAttendanceCount": 0,
      "historicalStatus": "No"
    },
    {
      "id": "4d_historical_041",
      "clubId": "club_001",
      "firstName": "Gina",
      "lastName": "Agostinho",
      "email": "agostinho.gina@gmail.com",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from historical student register",
      "sourceAttendanceCount": 0,
      "firstTimersPass": "No",
      "historicalStatus": "No"
    },
    {
      "id": "4d_historical_016",
      "clubId": "club_001",
      "firstName": "Graham",
      "lastName": "Everrett",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from historical student register",
      "sourceAttendanceCount": 0,
      "level": "2",
      "dateStarted": "17/01/2022",
      "firstTimersPass": "No",
      "historicalStatus": "No"
    },
    {
      "id": "4d_member_013",
      "clubId": "club_001",
      "firstName": "Graham",
      "lastName": "Pope",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Term pass",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Term 1, Free Nights, Mid Year Party",
      "sourceAttendanceCount": 7
    },
    {
      "id": "4d_member_047",
      "clubId": "club_001",
      "firstName": "Grant",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Party",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Mid Year Party",
      "sourceAttendanceCount": 0
    },
    {
      "id": "4d_member_014",
      "clubId": "club_001",
      "firstName": "Ian",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Term 1",
      "sourceAttendanceCount": 0
    },
    {
      "id": "4d_historical_046",
      "clubId": "club_001",
      "firstName": "Irene",
      "lastName": "Traynor",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from historical student register",
      "sourceAttendanceCount": 0,
      "referralSource": "Richard",
      "historicalStatus": "No"
    },
    {
      "id": "4d_member_015",
      "clubId": "club_001",
      "firstName": "Izzy",
      "lastName": "Rogers",
      "email": "rogers@outlook.com",
      "phone": "0468 643 974",
      "emergencyContactName": "Paul",
      "emergencyContactPhone": "0436 000 000",
      "status": "active",
      "pricingLabel": "Groupon",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Term 2, Special, Term 3, Mid Year Party",
      "sourceAttendanceCount": 14,
      "postcode": "5000",
      "emergencyContactRelationship": "Father"
    },
    {
      "id": "4d_member_017",
      "clubId": "club_001",
      "firstName": "Jake",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Free lesson",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Term 1",
      "sourceAttendanceCount": 1
    },
    {
      "id": "4d_historical_045",
      "clubId": "club_001",
      "firstName": "Janet",
      "lastName": "Pardis",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from historical student register",
      "sourceAttendanceCount": 0,
      "referralSource": "Meetup",
      "historicalStatus": "No"
    },
    {
      "id": "4d_member_018",
      "clubId": "club_001",
      "firstName": "Jeanette",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Term pass",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Term 1, Free Nights",
      "sourceAttendanceCount": 7
    },
    {
      "id": "4d_historical_050",
      "clubId": "club_001",
      "firstName": "Jeremy",
      "lastName": "Parker",
      "email": "jayjaybp@hotmail.com",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from historical student register",
      "sourceAttendanceCount": 0,
      "level": "1",
      "dateStarted": "24/4/2023",
      "referralSource": "meetup",
      "firstTimersPass": "yes",
      "historicalStatus": "No"
    },
    {
      "id": "4d_historical_017",
      "clubId": "club_001",
      "firstName": "Jessi",
      "lastName": "Hargrave",
      "email": "jessi.hargrave@gmail.com",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from historical student register",
      "sourceAttendanceCount": 0,
      "level": "2",
      "firstTimersPass": "yes",
      "historicalStatus": "No"
    },
    {
      "id": "4d_member_044",
      "clubId": "club_001",
      "firstName": "Jo",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Party",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Mid Year Party",
      "sourceAttendanceCount": 1
    },
    {
      "id": "4d_historical_018",
      "clubId": "club_001",
      "firstName": "Joanne",
      "lastName": "Allman",
      "email": "beal109@yahoo.com.au",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from historical student register",
      "sourceAttendanceCount": 0,
      "birthday": "6th Apr",
      "level": "2",
      "dateStarted": "14/3/2022",
      "referralSource": "Ceroc",
      "firstTimersPass": "Yes",
      "historicalStatus": "No"
    },
    {
      "id": "4d_member_035",
      "clubId": "club_001",
      "firstName": "John",
      "lastName": "Flynn",
      "email": "john@aflynn.net",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Free lesson",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Mid Year Party",
      "sourceAttendanceCount": 1,
      "birthday": "11th Apr",
      "level": "2",
      "dateStarted": "44655",
      "firstTimersPass": "Yes",
      "historicalStatus": "Staff"
    },
    {
      "id": "4d_member_050",
      "clubId": "club_001",
      "firstName": "Julianna",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Party",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Mid Year Party",
      "sourceAttendanceCount": 0
    },
    {
      "id": "4d_historical_047",
      "clubId": "club_001",
      "firstName": "Julie",
      "lastName": "Duffield",
      "email": "julieduffield1@bigpond.com",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from historical student register",
      "sourceAttendanceCount": 0,
      "referralSource": "Meetup Janet",
      "historicalStatus": "No"
    },
    {
      "id": "4d_historical_019",
      "clubId": "club_001",
      "firstName": "Karen",
      "lastName": "Miller",
      "email": "karmic.miller@gmail.com",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from historical student register",
      "sourceAttendanceCount": 0,
      "birthday": "11th Mar",
      "level": "2",
      "dateStarted": "25/10/2021",
      "firstTimersPass": "yes",
      "historicalStatus": "No"
    },
    {
      "id": "4d_member_028",
      "clubId": "club_001",
      "firstName": "Kate",
      "lastName": "Turner",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Free lesson",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Free Nights",
      "sourceAttendanceCount": 1
    },
    {
      "id": "4d_member_021",
      "clubId": "club_001",
      "firstName": "Kathy",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Free lesson",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Term 1",
      "sourceAttendanceCount": 0
    },
    {
      "id": "4d_historical_012",
      "clubId": "club_001",
      "firstName": "Kevin",
      "lastName": "Ward",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from historical student register",
      "sourceAttendanceCount": 0,
      "level": "1",
      "dateStarted": "44835",
      "firstTimersPass": "yes",
      "historicalStatus": "No"
    },
    {
      "id": "4d_historical_013",
      "clubId": "club_001",
      "firstName": "Kurt",
      "lastName": "Van Ryswyk",
      "email": "kurttruk2@gmail.com",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from historical student register",
      "sourceAttendanceCount": 0,
      "birthday": "18th Nov",
      "level": "1",
      "dateStarted": "44784",
      "referralSource": "Rita's friend",
      "firstTimersPass": "yes",
      "historicalStatus": "No"
    },
    {
      "id": "4d_member_022",
      "clubId": "club_001",
      "firstName": "Lauren",
      "lastName": "O'Brien",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Term pass",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Term 2, Term 1, Free Nights, Term 3",
      "sourceAttendanceCount": 0
    },
    {
      "id": "4d_member_037",
      "clubId": "club_001",
      "firstName": "Lea",
      "lastName": "Gambonnet",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Free lesson",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Mid Year Party",
      "sourceAttendanceCount": 1,
      "birthday": "3rd Aug",
      "level": "3",
      "dateStarted": "44207",
      "firstTimersPass": "no",
      "historicalStatus": "No"
    },
    {
      "id": "4d_member_008",
      "clubId": "club_001",
      "firstName": "Lexi",
      "lastName": "Cherry",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Term pass",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Free Nights, Term 2, Term 1, Special, Term 3, Mid Year Party",
      "sourceAttendanceCount": 9
    },
    {
      "id": "4d_historical_020",
      "clubId": "club_001",
      "firstName": "Liam",
      "lastName": "Maggee",
      "email": "liammagee@live.com.au",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from historical student register",
      "sourceAttendanceCount": 0,
      "level": "1",
      "dateStarted": "44745",
      "firstTimersPass": "Yes",
      "historicalStatus": "No"
    },
    {
      "id": "4d_member_011",
      "clubId": "club_001",
      "firstName": "Lilly",
      "lastName": "Ganegoda",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Term pass",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Free Nights, Term 2",
      "sourceAttendanceCount": 1
    },
    {
      "id": "4d_historical_021",
      "clubId": "club_001",
      "firstName": "Linda",
      "lastName": "Morris",
      "email": "gralinmorris@me.com",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from historical student register",
      "sourceAttendanceCount": 0,
      "dateStarted": "27/6/2022",
      "referralSource": "Meetup",
      "historicalStatus": "No"
    },
    {
      "id": "4d_member_032",
      "clubId": "club_001",
      "firstName": "Lindsey",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Free lesson",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Mid Year Party",
      "sourceAttendanceCount": 1
    },
    {
      "id": "4d_historical_022",
      "clubId": "club_001",
      "firstName": "Luke",
      "lastName": "Marshall",
      "email": "zeddicus87@hotmail.com",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from historical student register",
      "sourceAttendanceCount": 0,
      "birthday": "4th Dec",
      "level": "1",
      "dateStarted": "launch party",
      "firstTimersPass": "yes",
      "historicalStatus": "No"
    },
    {
      "id": "4d_member_039",
      "clubId": "club_001",
      "firstName": "Lyndee",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Free lesson",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Mid Year Party",
      "sourceAttendanceCount": 1
    },
    {
      "id": "4d_historical_049",
      "clubId": "club_001",
      "firstName": "Malcom",
      "lastName": "Dean",
      "email": "deansden1@gmail.com",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from historical student register",
      "sourceAttendanceCount": 0,
      "dateStarted": "44989",
      "referralSource": "Groupon",
      "firstTimersPass": "Yes",
      "historicalStatus": "No"
    },
    {
      "id": "4d_member_053",
      "clubId": "club_001",
      "firstName": "Maria",
      "lastName": "Kapsis",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Free lesson",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Term 3",
      "sourceAttendanceCount": 0
    },
    {
      "id": "4d_member_025",
      "clubId": "club_001",
      "firstName": "Mel",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Special",
      "sourceAttendanceCount": 1
    },
    {
      "id": "4d_member_036",
      "clubId": "club_001",
      "firstName": "Michael",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Free lesson",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Mid Year Party",
      "sourceAttendanceCount": 1
    },
    {
      "id": "4d_historical_023",
      "clubId": "club_001",
      "firstName": "Michael",
      "lastName": "Miller",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from historical student register",
      "sourceAttendanceCount": 0,
      "birthday": "31st Dec",
      "level": "2",
      "dateStarted": "25/10/2021",
      "firstTimersPass": "yes",
      "historicalStatus": "No"
    },
    {
      "id": "4d_historical_024",
      "clubId": "club_001",
      "firstName": "Michael",
      "lastName": "Siegele",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from historical student register",
      "sourceAttendanceCount": 0,
      "birthday": "12th Feb",
      "level": "3",
      "dateStarted": "44207",
      "firstTimersPass": "no",
      "historicalStatus": "No"
    },
    {
      "id": "4d_historical_025",
      "clubId": "club_001",
      "firstName": "Naila",
      "lastName": "Sherwani",
      "email": "nailasherwani@gmail.com",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from historical student register",
      "sourceAttendanceCount": 0,
      "historicalStatus": "No"
    },
    {
      "id": "4d_historical_026",
      "clubId": "club_001",
      "firstName": "Nas",
      "lastName": "Dharweesh",
      "email": "17anas@gmail.com",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from historical student register",
      "sourceAttendanceCount": 0,
      "birthday": "13th Dec",
      "level": "2",
      "dateStarted": "44809",
      "referralSource": "Ceroc",
      "firstTimersPass": "yes",
      "historicalStatus": "No"
    },
    {
      "id": "4d_member_030",
      "clubId": "club_001",
      "firstName": "Nathan",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Free lesson",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Mid Year Party",
      "sourceAttendanceCount": 1
    },
    {
      "id": "4d_member_016",
      "clubId": "club_001",
      "firstName": "Neil",
      "lastName": "Trout",
      "email": "chemistrytutor@chemist.com",
      "phone": "0414 393 824",
      "emergencyContactName": "Sue Trout",
      "emergencyContactPhone": "0417 838 460",
      "status": "active",
      "pricingLabel": "Groupon",
      "sessionBalance": 3,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Term 3, Term 2",
      "sourceAttendanceCount": 9,
      "postcode": "5042",
      "emergencyContactRelationship": "Spouse"
    },
    {
      "id": "4d_member_055",
      "clubId": "club_001",
      "firstName": "Nick",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Party",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Mid Year Party",
      "sourceAttendanceCount": 0
    },
    {
      "id": "4d_member_056",
      "clubId": "club_001",
      "firstName": "Nick",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Party",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Mid Year Party",
      "sourceAttendanceCount": 0
    },
    {
      "id": "4d_member_057",
      "clubId": "club_001",
      "firstName": "Nick",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Party",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Mid Year Party",
      "sourceAttendanceCount": 0
    },
    {
      "id": "4d_historical_043",
      "clubId": "club_001",
      "firstName": "Pat",
      "lastName": "Dansie",
      "email": "dansiepatricia@gmail.com",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from historical student register",
      "sourceAttendanceCount": 0,
      "historicalStatus": "No"
    },
    {
      "id": "4d_member_029",
      "clubId": "club_001",
      "firstName": "Paul",
      "lastName": "Cridge",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Groupon",
      "sessionBalance": 7,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Term 3",
      "sourceAttendanceCount": 1
    },
    {
      "id": "4d_member_034",
      "clubId": "club_001",
      "firstName": "Paula",
      "lastName": "Hutt",
      "email": "paula@aflynn.net",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Free lesson",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Mid Year Party",
      "sourceAttendanceCount": 1,
      "birthday": "28th June",
      "level": "2",
      "dateStarted": "44655",
      "referralSource": "Ceroc",
      "firstTimersPass": "Yes",
      "historicalStatus": "Staff"
    },
    {
      "id": "4d_historical_027",
      "clubId": "club_001",
      "firstName": "Pierre",
      "lastName": "Dumuid",
      "email": "pmdumuid@gmail.com",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from historical student register · Email note: 1 - collides wirh Monday night band 6 - as above 7 - m/j didn't teach me musical interpretation and just move after move. Ive moved to WCS to close that gap. Though plan to potentially pause dancing for a bit as heart is less in it.",
      "sourceAttendanceCount": 0,
      "birthday": "22nd Sept",
      "level": "2",
      "dateStarted": "launch party",
      "referralSource": "Ceroc",
      "firstTimersPass": "Yes",
      "historicalStatus": "No"
    },
    {
      "id": "4d_historical_048",
      "clubId": "club_001",
      "firstName": "Priah",
      "lastName": "Dean",
      "email": "deansden1@gmail.com",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from historical student register",
      "sourceAttendanceCount": 0,
      "dateStarted": "44989",
      "referralSource": "Groupon",
      "firstTimersPass": "yes",
      "historicalStatus": "No"
    },
    {
      "id": "4d_historical_044",
      "clubId": "club_001",
      "firstName": "Richard",
      "lastName": "Newton",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from historical student register",
      "sourceAttendanceCount": 0,
      "referralSource": "Facebook",
      "historicalStatus": "No"
    },
    {
      "id": "4d_member_033",
      "clubId": "club_001",
      "firstName": "Rita",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Free lesson",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Mid Year Party",
      "sourceAttendanceCount": 1
    },
    {
      "id": "4d_historical_028",
      "clubId": "club_001",
      "firstName": "Ryan",
      "lastName": "Harrison",
      "email": "ryan.thomas.harrison@gmail.com",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from historical student register",
      "sourceAttendanceCount": 0,
      "birthday": "29th Sept",
      "level": "2",
      "referralSource": "Ceroc",
      "firstTimersPass": "No",
      "historicalStatus": "No"
    },
    {
      "id": "4d_member_026",
      "clubId": "club_001",
      "firstName": "Samantha",
      "lastName": "Farrington",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Groupon",
      "sessionBalance": 7,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Term 3",
      "sourceAttendanceCount": 1
    },
    {
      "id": "4d_member_027",
      "clubId": "club_001",
      "firstName": "Seth",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Special",
      "sourceAttendanceCount": 1
    },
    {
      "id": "4d_member_031",
      "clubId": "club_001",
      "firstName": "Shae",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Free lesson",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Mid Year Party",
      "sourceAttendanceCount": 1
    },
    {
      "id": "4d_historical_040",
      "clubId": "club_001",
      "firstName": "Shariece",
      "lastName": "Maddern",
      "email": "ssmaddern@gmail.com",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from historical student register",
      "sourceAttendanceCount": 0,
      "level": "1",
      "dateStarted": "17/10/2022",
      "firstTimersPass": "no",
      "historicalStatus": "No"
    },
    {
      "id": "4d_historical_029",
      "clubId": "club_001",
      "firstName": "Sharon",
      "lastName": "Mills",
      "email": "shazzagaye@optusnet.com.au",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from historical student register",
      "sourceAttendanceCount": 0,
      "birthday": "2nd Oct",
      "level": "1",
      "dateStarted": "44745",
      "referralSource": "Wendy",
      "firstTimersPass": "Yes",
      "historicalStatus": "No"
    },
    {
      "id": "4d_member_043",
      "clubId": "club_001",
      "firstName": "Sonia",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Free lesson",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Mid Year Party, Free Nights",
      "sourceAttendanceCount": 1
    },
    {
      "id": "4d_member_046",
      "clubId": "club_001",
      "firstName": "Sotiri",
      "lastName": "Demitriou",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Free lesson",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Term 3",
      "sourceAttendanceCount": 0
    },
    {
      "id": "4d_historical_042",
      "clubId": "club_001",
      "firstName": "Stephanie",
      "lastName": "Cornish",
      "email": "stephanie.cornish@hotmail.com",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from historical student register",
      "sourceAttendanceCount": 0,
      "referralSource": "Dale friend",
      "historicalStatus": "No"
    },
    {
      "id": "4d_member_023",
      "clubId": "club_001",
      "firstName": "Sue",
      "lastName": "Trout",
      "email": "chemistrytutor@chemist.com",
      "phone": "0417 838 460",
      "emergencyContactName": "Neil Trout",
      "emergencyContactPhone": "0414 393 824",
      "status": "active",
      "pricingLabel": "Groupon",
      "sessionBalance": 3,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Term 3, Term 2",
      "sourceAttendanceCount": 9,
      "postcode": "5042",
      "emergencyContactRelationship": "Spouse"
    },
    {
      "id": "4d_historical_030",
      "clubId": "club_001",
      "firstName": "Sylvia",
      "lastName": "Allen",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from historical student register",
      "sourceAttendanceCount": 0,
      "dateStarted": "18/7/2022",
      "referralSource": "Groupon",
      "firstTimersPass": "Yes",
      "historicalStatus": "No"
    },
    {
      "id": "4d_member_004",
      "clubId": "club_001",
      "firstName": "Tanya",
      "lastName": "Stanton",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Term pass",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Term 3, Mid Year Party, Term 1, Special, Term 2, Free Nights",
      "sourceAttendanceCount": 1
    },
    {
      "id": "4d_historical_031",
      "clubId": "club_001",
      "firstName": "Tegan",
      "lastName": "Marshall",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from historical student register",
      "sourceAttendanceCount": 0,
      "birthday": "9th Feb",
      "level": "2",
      "dateStarted": "44835",
      "referralSource": "Ceroc",
      "firstTimersPass": "no",
      "historicalStatus": "No"
    },
    {
      "id": "4d_member_020",
      "clubId": "club_001",
      "firstName": "Tharuka",
      "lastName": "Nimeshani",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Free lesson",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Free Nights",
      "sourceAttendanceCount": 1
    },
    {
      "id": "4d_historical_032",
      "clubId": "club_001",
      "firstName": "Tom",
      "lastName": "Krajewski",
      "email": "tomjkra@gmail.com",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from historical student register",
      "sourceAttendanceCount": 0,
      "referralSource": "Groupon",
      "firstTimersPass": "Yes",
      "historicalStatus": "No"
    },
    {
      "id": "4d_historical_033",
      "clubId": "club_001",
      "firstName": "Tom",
      "lastName": "Reardon",
      "email": "tommoreardon@gmail.com",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from historical student register",
      "sourceAttendanceCount": 0,
      "birthday": "30th Apr",
      "level": "2",
      "dateStarted": "28/2/2022",
      "referralSource": "Ceroc",
      "firstTimersPass": "Yes",
      "historicalStatus": "No"
    },
    {
      "id": "4d_historical_034",
      "clubId": "club_001",
      "firstName": "Tracy",
      "lastName": "Skinner",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from historical student register",
      "sourceAttendanceCount": 0,
      "dateStarted": "19/12/2022",
      "historicalStatus": "No"
    },
    {
      "id": "4d_historical_035",
      "clubId": "club_001",
      "firstName": "Vanessa",
      "lastName": "W",
      "email": "nesswalter@gmail.com",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from historical student register",
      "sourceAttendanceCount": 0,
      "dateStarted": "44904",
      "historicalStatus": "No"
    },
    {
      "id": "4d_historical_037",
      "clubId": "club_001",
      "firstName": "Vicki",
      "lastName": "Barrett",
      "email": "vickibarrett@internode.on.net",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from historical student register",
      "sourceAttendanceCount": 0,
      "level": "1",
      "dateStarted": "44835",
      "firstTimersPass": "yes",
      "historicalStatus": "No"
    },
    {
      "id": "4d_member_019",
      "clubId": "club_001",
      "firstName": "Victoria",
      "lastName": "Luppino",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Free Nights, Term 1",
      "sourceAttendanceCount": 5
    },
    {
      "id": "4d_historical_053",
      "clubId": "club_001",
      "firstName": "Vincent",
      "lastName": "Messagean",
      "email": "vincent.messagean@gmail.com",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from historical student register · Email note: Address not found",
      "sourceAttendanceCount": 0,
      "historicalStatus": "No"
    },
    {
      "id": "4d_member_048",
      "clubId": "club_001",
      "firstName": "Virginia",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Party",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Mid Year Party",
      "sourceAttendanceCount": 0
    },
    {
      "id": "4d_historical_036",
      "clubId": "club_001",
      "firstName": "Vyx",
      "lastName": "Oz",
      "email": "vyxoz@icloud.com",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from historical student register",
      "sourceAttendanceCount": 0,
      "birthday": "10th Apr",
      "level": "1",
      "dateStarted": "launch party",
      "referralSource": "uni",
      "firstTimersPass": "yes",
      "historicalStatus": "No"
    },
    {
      "id": "4d_member_052",
      "clubId": "club_001",
      "firstName": "Wendee",
      "lastName": "Virgo",
      "email": "virg561@dodo.com.au",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Mid Year Party, Term 2 · Email note: Undelivered Mail Returned to Sender",
      "sourceAttendanceCount": 0,
      "birthday": "16th July",
      "level": "2",
      "dateStarted": "launch party",
      "firstTimersPass": "yes",
      "historicalStatus": "No"
    },
    {
      "id": "4d_historical_038",
      "clubId": "club_001",
      "firstName": "Wendy",
      "lastName": "Hardy",
      "email": "hardywr@yahoo.com.au",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from historical student register",
      "sourceAttendanceCount": 0,
      "birthday": "19th June",
      "level": "1",
      "dateStarted": "14/3/2022",
      "referralSource": "Ceroc",
      "firstTimersPass": "Yes",
      "historicalStatus": "No"
    },
    {
      "id": "4d_historical_039",
      "clubId": "club_001",
      "firstName": "Zacharlija",
      "lastName": "Standish",
      "email": "zrstandish1@gmail.com",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from historical student register",
      "sourceAttendanceCount": 0,
      "dateStarted": "26/9/2022",
      "historicalStatus": "No"
    },
    {
      "id": "4d_member_054",
      "clubId": "club_001",
      "firstName": "Zephy",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Free lesson",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Free Nights",
      "sourceAttendanceCount": 0
    }
  ],
  "sessions": [
    {
      "id": "4d_uat_2026_07_20",
      "clubId": "club_001",
      "title": "Monday",
      "sessionType": "Group class",
      "term": "2026 Term 3",
      "startDateTime": "2026-07-20T19:30:00+09:30",
      "endDateTime": "2026-07-20T21:30:00+09:30",
      "instructor": "Team",
      "location": "Mitcham Cultural Centre",
      "capacity": 60,
      "notes": "4D UAT session."
    }
  ]
};
