window.TRAKK_BOOTSTRAP = {
  "storageKey": "trakk-4d-uat-state-v1",
  "version": "0.11.0-4d-uat.1",
  "buildLabel": "4D UAT",
  "selectedSessionId": "4d_uat_2026_07_20",
  "members": [
    {
      "id": "4d_member_001",
      "clubId": "club_001",
      "firstName": "Aaron",
      "lastName": "Grierson",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Groupon",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Term 2, Special, Term 3, Mid Year Party",
      "sourceAttendanceCount": 14
    },
    {
      "id": "4d_member_051",
      "clubId": "club_001",
      "firstName": "Abby",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Party",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Mid Year Party",
      "sourceAttendanceCount": 0
    },
    {
      "id": "4d_member_038",
      "clubId": "club_001",
      "firstName": "Adam",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Free lesson",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Mid Year Party",
      "sourceAttendanceCount": 1
    },
    {
      "id": "4d_member_003",
      "clubId": "club_001",
      "firstName": "Andrew",
      "lastName": "Fort",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Groupon",
      "sessionBalance": 7,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Special, Term 3",
      "sourceAttendanceCount": 2
    },
    {
      "id": "4d_member_042",
      "clubId": "club_001",
      "firstName": "Ann",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Party",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Mid Year Party",
      "sourceAttendanceCount": 1
    },
    {
      "id": "4d_member_002",
      "clubId": "club_001",
      "firstName": "Anna",
      "lastName": "Fort",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Groupon",
      "sessionBalance": 7,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Term 3, Special",
      "sourceAttendanceCount": 2
    },
    {
      "id": "4d_member_005",
      "clubId": "club_001",
      "firstName": "Bec",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Special, Mid Year Party",
      "sourceAttendanceCount": 1
    },
    {
      "id": "4d_member_006",
      "clubId": "club_001",
      "firstName": "Bridgette",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "8 class pass",
      "sessionBalance": 7,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Term 2, Mid Year Party",
      "sourceAttendanceCount": 1
    },
    {
      "id": "4d_member_045",
      "clubId": "club_001",
      "firstName": "Carey",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Party",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Mid Year Party",
      "sourceAttendanceCount": 0
    },
    {
      "id": "4d_member_007",
      "clubId": "club_001",
      "firstName": "Catherine",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Term 1",
      "sourceAttendanceCount": 0
    },
    {
      "id": "4d_member_049",
      "clubId": "club_001",
      "firstName": "Cathy",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Party",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Mid Year Party",
      "sourceAttendanceCount": 0
    },
    {
      "id": "4d_member_040",
      "clubId": "club_001",
      "firstName": "Dale",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Free lesson",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Mid Year Party",
      "sourceAttendanceCount": 1
    },
    {
      "id": "4d_member_058",
      "clubId": "club_001",
      "firstName": "Daniel",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Party",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Mid Year Party",
      "sourceAttendanceCount": 0
    },
    {
      "id": "4d_member_059",
      "clubId": "club_001",
      "firstName": "Daniel",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Party",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Mid Year Party",
      "sourceAttendanceCount": 0
    },
    {
      "id": "4d_member_041",
      "clubId": "club_001",
      "firstName": "David",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Party",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Mid Year Party",
      "sourceAttendanceCount": 1
    },
    {
      "id": "4d_member_012",
      "clubId": "club_001",
      "firstName": "Dylan",
      "lastName": "Horn",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Free lesson",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Free Nights",
      "sourceAttendanceCount": 1
    },
    {
      "id": "4d_member_009",
      "clubId": "club_001",
      "firstName": "Eranga",
      "lastName": "Kompannage",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Term pass",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Term 2",
      "sourceAttendanceCount": 0
    },
    {
      "id": "4d_member_024",
      "clubId": "club_001",
      "firstName": "Eranga",
      "lastName": "Sudeshini",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Free lesson",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Free Nights",
      "sourceAttendanceCount": 1
    },
    {
      "id": "4d_member_010",
      "clubId": "club_001",
      "firstName": "Fiona",
      "lastName": "Clewes",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Free Nights, Term 1, Special, Term 2, Term 3",
      "sourceAttendanceCount": 4
    },
    {
      "id": "4d_member_013",
      "clubId": "club_001",
      "firstName": "Graham",
      "lastName": "Pope",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Term pass",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Term 1, Free Nights, Mid Year Party",
      "sourceAttendanceCount": 7
    },
    {
      "id": "4d_member_047",
      "clubId": "club_001",
      "firstName": "Grant",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Party",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Mid Year Party",
      "sourceAttendanceCount": 0
    },
    {
      "id": "4d_member_014",
      "clubId": "club_001",
      "firstName": "Ian",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Term 1",
      "sourceAttendanceCount": 0
    },
    {
      "id": "4d_member_015",
      "clubId": "club_001",
      "firstName": "Izzy",
      "lastName": "Rogers",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Groupon",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Term 2, Special, Term 3, Mid Year Party",
      "sourceAttendanceCount": 14
    },
    {
      "id": "4d_member_017",
      "clubId": "club_001",
      "firstName": "Jake",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Free lesson",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Term 1",
      "sourceAttendanceCount": 1
    },
    {
      "id": "4d_member_018",
      "clubId": "club_001",
      "firstName": "Jeanette",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Term pass",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Term 1, Free Nights",
      "sourceAttendanceCount": 7
    },
    {
      "id": "4d_member_044",
      "clubId": "club_001",
      "firstName": "Jo",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Party",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Mid Year Party",
      "sourceAttendanceCount": 1
    },
    {
      "id": "4d_member_035",
      "clubId": "club_001",
      "firstName": "John",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Free lesson",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Mid Year Party",
      "sourceAttendanceCount": 1
    },
    {
      "id": "4d_member_050",
      "clubId": "club_001",
      "firstName": "Julianna",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Party",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Mid Year Party",
      "sourceAttendanceCount": 0
    },
    {
      "id": "4d_member_028",
      "clubId": "club_001",
      "firstName": "Kate",
      "lastName": "Turner",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Free lesson",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Free Nights",
      "sourceAttendanceCount": 1
    },
    {
      "id": "4d_member_021",
      "clubId": "club_001",
      "firstName": "Kathy",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Free lesson",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Term 1",
      "sourceAttendanceCount": 0
    },
    {
      "id": "4d_member_022",
      "clubId": "club_001",
      "firstName": "Lauren",
      "lastName": "O'Brien",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Term pass",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Term 2, Term 1, Free Nights, Term 3",
      "sourceAttendanceCount": 0
    },
    {
      "id": "4d_member_037",
      "clubId": "club_001",
      "firstName": "Lea",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Free lesson",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Mid Year Party",
      "sourceAttendanceCount": 1
    },
    {
      "id": "4d_member_008",
      "clubId": "club_001",
      "firstName": "Lexi",
      "lastName": "Cherry",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Term pass",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Free Nights, Term 2, Term 1, Special, Term 3, Mid Year Party",
      "sourceAttendanceCount": 9
    },
    {
      "id": "4d_member_011",
      "clubId": "club_001",
      "firstName": "Lilly",
      "lastName": "Ganegoda",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Term pass",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Free Nights, Term 2",
      "sourceAttendanceCount": 1
    },
    {
      "id": "4d_member_032",
      "clubId": "club_001",
      "firstName": "Lindsey",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Free lesson",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Mid Year Party",
      "sourceAttendanceCount": 1
    },
    {
      "id": "4d_member_039",
      "clubId": "club_001",
      "firstName": "Lyndee",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Free lesson",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Mid Year Party",
      "sourceAttendanceCount": 1
    },
    {
      "id": "4d_member_053",
      "clubId": "club_001",
      "firstName": "Maria",
      "lastName": "Kapsis",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Free lesson",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Term 3",
      "sourceAttendanceCount": 0
    },
    {
      "id": "4d_member_025",
      "clubId": "club_001",
      "firstName": "Mel",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Special",
      "sourceAttendanceCount": 1
    },
    {
      "id": "4d_member_036",
      "clubId": "club_001",
      "firstName": "Michael",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Free lesson",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Mid Year Party",
      "sourceAttendanceCount": 1
    },
    {
      "id": "4d_member_030",
      "clubId": "club_001",
      "firstName": "Nathan",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Free lesson",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Mid Year Party",
      "sourceAttendanceCount": 1
    },
    {
      "id": "4d_member_016",
      "clubId": "club_001",
      "firstName": "Neil",
      "lastName": "Trout",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Groupon",
      "sessionBalance": 3,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Term 3, Term 2",
      "sourceAttendanceCount": 9
    },
    {
      "id": "4d_member_055",
      "clubId": "club_001",
      "firstName": "Nick",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Party",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Mid Year Party",
      "sourceAttendanceCount": 0
    },
    {
      "id": "4d_member_056",
      "clubId": "club_001",
      "firstName": "Nick",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Party",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Mid Year Party",
      "sourceAttendanceCount": 0
    },
    {
      "id": "4d_member_057",
      "clubId": "club_001",
      "firstName": "Nick",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Party",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Mid Year Party",
      "sourceAttendanceCount": 0
    },
    {
      "id": "4d_member_029",
      "clubId": "club_001",
      "firstName": "Paul",
      "lastName": "Cridge",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Groupon",
      "sessionBalance": 7,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Term 3",
      "sourceAttendanceCount": 1
    },
    {
      "id": "4d_member_034",
      "clubId": "club_001",
      "firstName": "Paula",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Free lesson",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Mid Year Party",
      "sourceAttendanceCount": 1
    },
    {
      "id": "4d_member_033",
      "clubId": "club_001",
      "firstName": "Rita",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Free lesson",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Mid Year Party",
      "sourceAttendanceCount": 1
    },
    {
      "id": "4d_member_026",
      "clubId": "club_001",
      "firstName": "Samantha",
      "lastName": "Farrington",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Groupon",
      "sessionBalance": 7,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Term 3",
      "sourceAttendanceCount": 1
    },
    {
      "id": "4d_member_027",
      "clubId": "club_001",
      "firstName": "Seth",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Special",
      "sourceAttendanceCount": 1
    },
    {
      "id": "4d_member_031",
      "clubId": "club_001",
      "firstName": "Shae",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Free lesson",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Mid Year Party",
      "sourceAttendanceCount": 1
    },
    {
      "id": "4d_member_043",
      "clubId": "club_001",
      "firstName": "Sonia",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Free lesson",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Mid Year Party, Free Nights",
      "sourceAttendanceCount": 1
    },
    {
      "id": "4d_member_046",
      "clubId": "club_001",
      "firstName": "Sotiri",
      "lastName": "Demitriou",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Free lesson",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Term 3",
      "sourceAttendanceCount": 0
    },
    {
      "id": "4d_member_023",
      "clubId": "club_001",
      "firstName": "Sue",
      "lastName": "Trout",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Groupon",
      "sessionBalance": 3,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Term 3, Term 2",
      "sourceAttendanceCount": 9
    },
    {
      "id": "4d_member_004",
      "clubId": "club_001",
      "firstName": "Tanya",
      "lastName": "Stanton",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Term pass",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Term 3, Mid Year Party, Term 1, Special, Term 2, Free Nights",
      "sourceAttendanceCount": 1
    },
    {
      "id": "4d_member_020",
      "clubId": "club_001",
      "firstName": "Tharuka",
      "lastName": "Nimeshani",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Free lesson",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Free Nights",
      "sourceAttendanceCount": 1
    },
    {
      "id": "4d_member_019",
      "clubId": "club_001",
      "firstName": "Victoria",
      "lastName": "Luppino",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Free Nights, Term 1",
      "sourceAttendanceCount": 5
    },
    {
      "id": "4d_member_048",
      "clubId": "club_001",
      "firstName": "Virginia",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "inactive",
      "pricingLabel": "Party",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Mid Year Party",
      "sourceAttendanceCount": 0
    },
    {
      "id": "4d_member_052",
      "clubId": "club_001",
      "firstName": "Wendee",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Single class",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Mid Year Party, Term 2",
      "sourceAttendanceCount": 0
    },
    {
      "id": "4d_member_054",
      "clubId": "club_001",
      "firstName": "Zephy",
      "lastName": "",
      "email": "",
      "phone": "",
      "emergencyContactName": "",
      "emergencyContactPhone": "",
      "status": "active",
      "pricingLabel": "Free lesson",
      "sessionBalance": 0,
      "memberType": "member",
      "learningPreference": "Both",
      "notes": "Imported from 2026 sign-in sheet · Free Nights",
      "sourceAttendanceCount": 0
    }
  ],
  "sessions": [
    {
      "id": "4d_uat_2026_07_20",
      "clubId": "club_001",
      "title": "Monday",
      "sessionType": "Group class",
      "term": "2026 Term 3",
      "startDateTime": "2026-07-20T19:30:00+09:30",
      "endDateTime": "2026-07-20T21:30:00+09:30",
      "instructor": "Team",
      "location": "Mitcham Cultural Centre",
      "capacity": 60,
      "notes": "4D UAT session."
    }
  ]
};
